### ISSUE TITLE
Refactor for 1.0

### ISSUE THREAD

**Issue by madeleineostoja** [SimplaElements/simpla-markdown#18]
This issue covers everything needed for simpla-markdown to hit 1.0, both in terms of fixes/enhancements and upstream blockers.

Blockers:

- [ ] `select` filter on Simpla SDK gets (for #16)
- [ ] Lightweight markdown editor component (for #14)
- [ ] Simpla Anchor behavior (for #13 and #9)
- [ ] Simpla WC v1 / Polymer 2 support

Refactors:

- [ ] Replace SimpleMDE with lightweight editor ( #14 )
- [ ] Replace HTML -> MD with split data ( #16 )
- [ ] Position editor with JS rather than relative to parent ( #13, #9 )
- [ ] Polish editor UI ( #15 )
- [ ] Resources & tests ( #3, #4 )
- [ ] Port to pure Polymer 2 or Skate component
